apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwl-wim-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nwl-wim-service
  template:
    metadata:
      labels:
        app: nwl-wim-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "nwl-wim-service"
        vault.hashicorp.com/agent-inject-secret-env: "secret/data/test/nwl-wim-service"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "secret/data/test/nwl-wim-service" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end }}
        vault.hashicorp.com/auth-audience: "vault"
    spec:
      serviceAccountName: nwl-wim-sa
      containers:
        - name: app
          image: 10.15.15.116:32500/nwl-wim-service:latest
          ports:
            - containerPort: 3000
          command:
            - /bin/sh
            - -c
            - |
              source /vault/secrets/env
              exec node dist/main.js
